# Generated by Django 5.1.2 on 2024-10-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmapping',
            old_name='short_code',
            new_name='short_url',
        ),
    ]
