# Generated by Django 5.1.2 on 2024-10-29 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_short_code_urlmapping_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='urlmapping',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
